### ISSUE TITLE
Deterministic build

### ISSUE THREAD

**Issue by fazibear** [nerves-project/shoehorn#30]
Looks like the shoehorn.boot script is different every single build. While the content is still the same, the order is different. This will affect HMAC calculation for example. 

What is the source code of that script? How can I make this file deterministic?

Thanks for you help.

This is a image of the part of diff.
![Screen Shot 2019-09-23 at 14 06 42](https://user-images.githubusercontent.com/687/65424435-d8834980-de0b-11e9-80aa-4e521373fc99.png)

**Comment by fhunleth** [comment]
I don't know the answers, but thank you!!!! This is important to me too!

**Comment by mobileoverlord** [comment]
The boot script is being generated by`:systools.make_script/2` by Mix releases https://github.com/elixir-lang/elixir/blob/v1.9.1/lib/mix/lib/mix/release.ex#L435-L470

I wonder if this is a result of the data being given to `:systools.make_script/2` not being ordered or if `:systools.make_script/2` has variability. @josevalim might have some insight while this is checked.

**Comment by josevalim** [comment]
Can someone please try changing this line:

https://github.com/elixir-lang/elixir/blob/v1.9.1/lib/mix/lib/mix/release.ex#L496

To do:

    Enum.sort(rel_apps)

? If it removes the issue, then we know the answer. :)

**Comment by fazibear** [comment]
Hi, Definitively this is it. Tried lot of times with `Enum.sort` and always got same md5sum for the boot scripts. Should I make a PR with such a change?

**Comment by fhunleth** [comment]
@fazibear Thanks for following up on this! I'm not José, but I think that you should definitely make a PR with the change and then if there are issues, they can be worked out in that PR.
