### ISSUE TITLE
Firmware fails to start with custom config provider

### ISSUE THREAD

**Issue by jeanparpaillon** [nerves-project/shoehorn#57]
### Environment

* Elixir version (`elixir -v`): 1.11.3-otp-23 / erlang 23.3.4.1

### Current behavior

I want to use a custom config provider in my firmware, as in https://hexdocs.pm/elixir/1.11.4/Config.Provider.html#content

When adding it to the `config_providers` option of the firmware release, the firmware crashes with the following:

```
could not fetch environment variable "RELEASE_SYS_CONFIG" because it is not set
```

(see attached screenshot for more details)

### Expected behavior

Firmware starts and loads compile time config, `runtime.exs` + custom config provider

I am not sure if it is related to `shoehorn` or `nerves_runtime` however. Has custom config providers already been tested with nerves ?

**Comment by fhunleth** [comment]
I have not used custom config providers. Could you update to a newer version of Erlang and Elixir just in case anything has changed since 1.11/23.3?

**Comment by axelson** [comment]
Custom providers should work, I've used it before. Here's the issue where support was initially added: https://github.com/nerves-project/nerves/issues/632

**Comment by jeanparpaillon** [comment]
@fhunleth @axelson thanks for your support, I am backporting erlinit 1.11.0  into my BSP, that should do the trick.

Anyway, closing as not related to shoehorn
